# Generated by Django 3.1.2 on 2020-10-28 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_tupe',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.producttype'),
            preserve_default=False,
        ),
    ]
