# Generated by Django 3.1.2 on 2020-10-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_products_product_tupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_tupe',
            new_name='product_type',
        ),
    ]
