# Generated by Django 3.1.2 on 2020-10-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_mycart'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='purchesed',
            field=models.BooleanField(default=False),
        ),
    ]
