# Generated by Django 3.1.3 on 2020-11-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201123_1511'),
        ('market', '0007_mycart_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.useraddress'),
        ),
    ]
