# Generated by Django 3.1.3 on 2020-11-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_mycart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='status',
            field=models.CharField(blank=True, choices=[('AR', 'Arriving'), ('OP', 'Order placed'), ('PS', 'Package shipped'), ('ID', 'Item delivered')], default=None, max_length=2, null=True),
        ),
    ]
