# Generated by Django 3.1.3 on 2020-11-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20201127_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='status',
            field=models.CharField(blank=True, choices=[('OP', 'Order placed'), ('AR', 'Arriving'), ('PS', 'Package shipped'), ('ID', 'Item delivered')], default=None, max_length=2, null=True),
        ),
    ]
