# Generated by Django 3.1.3 on 2020-11-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20201129_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.products'),
        ),
    ]
