# Generated by Django 3.1.2 on 2020-11-22 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_accounts_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('house_no', models.IntegerField(verbose_name='House Number')),
                ('area', models.CharField(max_length=255, verbose_name='Local Area')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('pincode', models.IntegerField(verbose_name='Postal Code')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accounts')),
            ],
        ),
    ]
