# Generated by Django 3.1.2 on 2020-11-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201122_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='useDefault',
            field=models.BooleanField(default=False),
        ),
    ]
