# Generated by Django 3.1.2 on 2020-11-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_useraddress_moibile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='moibile',
            new_name='mobile',
        ),
    ]
