# Generated by Django 3.1.3 on 2020-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201123_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
